-- drop database VigiaEnchente;
create database IF not exists VigiaEnchente;
use VigiaEnchente;

create table if not exists users (
    id_user INT AUTO_INCREMENT PRIMARY KEY,
    nome varchar(100) NOT NULL,
    email varchar(100) UNIQUE NOT NULL,
    phone varchar(15) UNIQUE NOT NULL,
    senha varchar(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table if not exists address (
    id_address INT AUTO_INCREMENT PRIMARY KEY,
    id_address_user INT UNIQUE,
    rua VARCHAR(100) NOT NULL,
    num_rua VARCHAR(10),
    cep VARCHAR(8) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    FOREIGN KEY (id_address_user) REFERENCES users(id_user)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

create table if not exists subscriptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    endpoint TEXT NOT NULL,
    p256dh TEXT,
    auth TEXT,
    user_id INT,
    payload TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id_user)
);

create table if not exists message (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    date_msg DATE,
    hour_msg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content_msg TEXT(4096),
    foreign key (user_id) references users(id_user)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

create table if not exists alert (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date_alert DATE,
    hour_alert TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content_alert TEXT(4096),
    message_id INT,
    foreign key (message_id) references message(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- Spring Session tables
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB;